# Generated by Django 5.1.15 on 2026-09-10 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPasswordHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password_hash", models.CharField(max_length=255, verbose_name="password hash")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creataed at")),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Set the date when the password expires and the user will be required to change it. Leave empty for a password that never expires.",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
